### ISSUE TITLE
Tool tip cut off on edge of page

### ISSUE THREAD

**Issue by tracfren** [awslabs/synchro-charts#157]
**Describe the bug**
When a visualization is on the right edge of a page and you hover over data on the right side of the visualization, the tool tip extends beyond the edge of the page and the tool tip is cut in half. When this happens, you can't see the values of the data streams you are trying to inspect.

**To Reproduce**
1. Place a visualization on the right edge of a page.
2. Hover over the data streams.
3. View the tool tip cut in half.

**Expected behavior**
The data should be completely visible and the tool tip shouldn't extend the left and right boundaries of the visualization. Can the tool tip flip direction when it nears the boundary?

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/67283114/185677934-cc5281e0-27e0-4ae9-8b19-20d30610b19d.png)

**Comment by diehbria** [comment]
Fixed within https://github.com/awslabs/synchro-charts/pull/158, fix will be released within https://github.com/awslabs/synchro-charts/pull/159 (v6.0.1)
