### ISSUE TITLE
Y-axis values cut off past 5 digits in charts 

### ISSUE THREAD

**Issue by luo-anthony-aws** [awslabs/synchro-charts#66]
In charts, if the y-axis value exceeds 5 digits (EX: 120,000) the value will be cutoff starting from the left-most digits (EX: 120,000 will appear as 20,000)

![image](https://user-images.githubusercontent.com/86490240/129243451-32eb6e6d-174b-4fb2-bc78-2b1e973e6d23.png)

**Comment by corteggiano** [comment]
grabbing this!

**Comment by corteggiano** [comment]
fixed in [#175](https://github.com/awslabs/synchro-charts/pull/175) and released in version [6.0.5](https://github.com/awslabs/synchro-charts/pull/177)
