### ISSUE TITLE
Inaccessible Link for Github Actions example in CONTRIBUTING.md

### ISSUE THREAD

**Issue by luo-anthony** [awslabs/synchro-charts#94]
In `CONTRIBUTING.md` under section **Contributing via Pull Requests** in section 5.3 the link for '[Example of modified GitHub actions to include snapshot.](https://github.com/diehbria/aws-synchro-charts/blob/0610b552b284f0f54ae059ee35fb5fa5ad036221/.github/workflows/github-actions.yml)' is not accessible (returns a 404 Page Not Found error). 

> iii. If your pull request adds cypress integration tests which perform a snapshot, the snapshots must be created within the CI process. To achieve this, you will need to temporarily alter the GitHub workflow to generate and persist snapshots. Create a pull request within your own forked version of Synchro Charts. Once the tests complete, it will provide you with a file containing the generated snapshots. Take these generated snapshots, manually confirm they look correct, and then add them to the repository. Revert any changes made to the GitHub actions, and now you have correctly generated new snapshots! **[Example of modified GitHub actions to include snapshot](https://github.com/diehbria/aws-synchro-charts/blob/0610b552b284f0f54ae059ee35fb5fa5ad036221/.github/workflows/github-actions.yml)**.

**Comment by chejimmy** [comment]
the link '[Example of modified GitHub actions to include snapshot.](https://github.com/diehbria/aws-synchro-charts/blob/0610b552b284f0f54ae059ee35fb5fa5ad036221/.github/workflows/github-actions.yml)' is pointing to https://github.com/diehbria/aws-synchro-charts/blob/0610b552b284f0f54ae059ee35fb5fa5ad036221/.github/workflows/github-actions.yml and it is working now.
