### ISSUE TITLE
Annotation Jumps Around

### ISSUE THREAD

**Issue by occhangg** [awslabs/synchro-charts#95]
**Describe the bug**
When you have multiple charts and have multiple annotations in each of the chart, changing an annotation via dragging would cause another annotation to jump around. See video.

I think this affects thresholds too.

**To Reproduce**
1. Go to https://synchrocharts.com/#/Features/Annotation
2. Click around the annotations. See video

**Expected behavior**
Maybe not have the annotation jump around when its not being dragged?

Or, if they are all in the same group, maybe changing one annotation would automatically change all the other chart's annotation to have it sync up. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac Big Sur 11.6 (20G165)
 - Browser: chrome
 - Version 94.0.4606.97

**Additional context**
Add any other context about the problem here

https://user-images.githubusercontent.com/80849383/137533684-a4738d95-f17d-4011-ae8c-443a56f6bf61.mov

.

**Comment by occhangg** [comment]
Thanks for looking into this.

**Comment by diehbria** [comment]
Able to fix it locally by altering how we set the `internalAnnotations` within the `webgl-base-chart` to clone, as well as tweak some of the base-chart lifecycle code around when to update internal annotations. Will provide a pull request later this week to resolve this issue.

**Comment by diehbria** [comment]
documentation site deployed, manually confirmed issue no longer is demonstrated within the annotation dragging example.
